[tools]
"http:tailwindcss" = { version = "4.3.3", url = "https://github.com/tailwindlabs/tailwindcss/releases/download/v{{ version }}/tailwindcss-linux-{{ arch() }}" }
just = "latest"
k6 = "1.6.0"
sqlite = "3.51.2"
uv = "0.10.8"

# "npm:chromium" = "latest"
# "npm:lighthouse" = "latest"

# [env]
# CHROME_PATH = { value = "{{ exec(command='mise where npm:chromium') }}/lib/node_modules/chromium/lib/chromium/chrome-linux/chrome", tools = true }
