"""add rescraped at

Revision ID: 015faf174cb5
Revises: e5534c6064e2
Create Date: 2025-11-04 14:07:31.966053

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "015faf174cb5"
down_revision: Union[str, Sequence[str], None] = "e5534c6064e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lastcleanup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lastcleanup")
    # ### end Alembic commands ###
