"""remove golden owl

Revision ID: 0df0314ed5c3
Revises: a007ce80b4cb
Create Date: 2025-10-19 19:49:13.481477

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0df0314ed5c3"
down_revision: Union[str, Sequence[str], None] = "a007ce80b4cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lecturer", schema=None) as batch_op:
        batch_op.drop_column("golden_owl")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lecturer", schema=None) as batch_op:
        batch_op.add_column(sa.Column("golden_owl", sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
