"""add unit type

Revision ID: 1aef6b22e4e2
Revises: 0df0314ed5c3
Create Date: 2025-10-20 14:18:07.921778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1aef6b22e4e2"
down_revision: Union[str, Sequence[str], None] = "0df0314ed5c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM unitsectionlink"))
    op.create_table(
        "unittypelegends",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("semkez", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("legend", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("unitsectionlink", schema=None) as batch_op:
        batch_op.add_column(sa.Column("type_id", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("unitsectionlink", schema=None) as batch_op:
        batch_op.drop_column("type_id")

    op.drop_table("unittypelegends")
    # ### end Alembic commands ###
