"""initial models

Revision ID: 286444bb10a5
Revises: 
Create Date: 2025-10-14 08:48:10.202263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '286444bb10a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachingunit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('O', 'WPlus', 'W', 'EMinus', 'Z', 'Dr', name='unittypeenum'), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('semester', sa.Enum('HS', 'FS', name='semesterenum'), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('learning_objective', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lecture_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('literature', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('competencies', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('examination_block', sa.JSON(), nullable=True),
    sa.Column('ects_credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('teaching_unit_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='weekdayenum'), nullable=False),
    sa.Column('start', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('V', 'G', 'U', 'S', 'K', 'P', 'A', 'D', 'R', name='coursetypeenum'), nullable=False),
    sa.Column('first_half_semester', sa.Boolean(), nullable=False),
    sa.Column('second_half_semester', sa.Boolean(), nullable=False),
    sa.Column('two_weekly', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['teaching_unit_id'], ['teachingunit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courselecturerrelations',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'lecturer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courselecturerrelations')
    op.drop_table('course')
    op.drop_table('teachingunit')
    op.drop_table('lecturer')
    # ### end Alembic commands ###
