"""add indices for key columns like title/credits

Revision ID: 28d83f5b9096
Revises: c87f2be09719
Create Date: 2026-02-20 11:08:42.403946

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28d83f5b9096"
down_revision: Union[str, Sequence[str], None] = "c87f2be09719"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("learningunit", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_learningunit_credits"), ["credits"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learningunit_number"), ["number"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learningunit_semkez"), ["semkez"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learningunit_title"), ["title"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learningunit_title_english"), ["title_english"], unique=False
        )

    with op.batch_alter_table("lecturer", schema=None) as batch_op:
        batch_op.create_index(
            "idx_lecturer_name_surname", ["name", "surname"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_lecturer_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_lecturer_surname"), ["surname"], unique=False
        )

    with op.batch_alter_table("unitsectionlink", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_unitsectionlink_type"), ["type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("unitsectionlink", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_unitsectionlink_type"))

    with op.batch_alter_table("lecturer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lecturer_surname"))
        batch_op.drop_index(batch_op.f("ix_lecturer_name"))
        batch_op.drop_index("idx_lecturer_name_surname")

    with op.batch_alter_table("learningunit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learningunit_title_english"))
        batch_op.drop_index(batch_op.f("ix_learningunit_title"))
        batch_op.drop_index(batch_op.f("ix_learningunit_semkez"))
        batch_op.drop_index(batch_op.f("ix_learningunit_number"))
        batch_op.drop_index(batch_op.f("ix_learningunit_credits"))

    # ### end Alembic commands ###
