"""remove unitchanges

Revision ID: 2c332002ee3f
Revises: 3b1a337a1fe5
Create Date: 2026-03-02 17:17:30.233013

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c332002ee3f"
down_revision: Union[str, Sequence[str], None] = "3b1a337a1fe5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unitchanges")
    op.execute("VACUUM")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unitchanges",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("unit_id", sa.INTEGER(), nullable=False),
        sa.Column("changes", sqlite.JSON(), nullable=True),
        sa.Column("scraped_at", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
