"""add latest semkez table

Revision ID: 33e0846c3903
Revises: b014bbd52431
Create Date: 2026-08-06 11:58:30.741752

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33e0846c3903"
down_revision: Union[str, Sequence[str], None] = "b014bbd52431"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "latestsemkez",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("semkez", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scraped_at", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("latestsemkez")
    # ### end Alembic commands ###
