"""move over cleanup table

Revision ID: 3b1a337a1fe5
Revises: aa860aba0a9f
Create Date: 2026-02-27 19:18:10.668579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b1a337a1fe5'
down_revision: Union[str, Sequence[str], None] = 'aa860aba0a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lastcleanup')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lastcleanup',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
