"""golden owl

Revision ID: 40a2a6a4691a
Revises: 286444bb10a5
Create Date: 2025-10-14 10:25:56.688468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40a2a6a4691a"
down_revision: Union[str, Sequence[str], None] = "286444bb10a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lecturer", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "golden_owl", sa.Boolean(), nullable=False, server_default=sa.text("0")
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lecturer", schema=None) as batch_op:
        batch_op.drop_column("golden_owl")

    # ### end Alembic commands ###
