"""completed semesters

Revision ID: 497216f8f2a4
Revises: 469a31ddd9b4
Create Date: 2025-10-29 16:49:18.135911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "497216f8f2a4"
down_revision: Union[str, Sequence[str], None] = "469a31ddd9b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "finishedscrapingsemester",
        sa.Column("semkez", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("semkez"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("finishedscrapingsemester")
    # ### end Alembic commands ###
