"""materialized table for section paths

Revision ID: 4a9111aae04a
Revises: b6c0d8f67343
Create Date: 2026-02-20 14:41:34.046338

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a9111aae04a"
down_revision: Union[str, Sequence[str], None] = "b6c0d8f67343"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sectionpathview",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path_en", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("path_de", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sectionpathview", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sectionpathview_path_de"), ["path_de"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sectionpathview_path_en"), ["path_en"], unique=False
        )

    op.execute("""
        INSERT INTO sectionpathview (id, path_en, path_de)
        WITH RECURSIVE section_paths(id, parent_id, path_en, path_de) AS
            (SELECT section.id AS id,
                    section.parent_id AS parent_id,
                    section.name_english AS path_en,
                    section.name AS path_de
            FROM SECTION
            WHERE section.parent_id IS NULL
            UNION ALL SELECT section_1.id AS id,
                            section_1.parent_id AS parent_id,
                            section_paths.path_en || ' > ' || section_1.name_english AS path_en,
                            section_paths.path_de || ' > ' || section_1.name AS path_de
            FROM SECTION AS section_1
            JOIN section_paths ON section_1.parent_id = section_paths.id)
        SELECT id, path_en, path_de FROM section_paths;
        """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sectionpathview", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sectionpathview_path_en"))
        batch_op.drop_index(batch_op.f("ix_sectionpathview_path_de"))

    op.drop_table("sectionpathview")
    # ### end Alembic commands ###
