"""rename code to number, add dept/level

Revision ID: 76c252644a17
Revises: 1aef6b22e4e2
Create Date: 2025-10-20 18:40:59.598649

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "76c252644a17"
down_revision: Union[str, Sequence[str], None] = "1aef6b22e4e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.create_unique_constraint("course_number_semkez", ["number", "semkez"])
        batch_op.drop_column("code")

    with op.batch_alter_table("learningunit", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(sa.Column("levels", sa.JSON(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "department",
                sa.Enum(
                    "ARCHITECTURE",
                    "CIVIL_ENVIRONMENTAL_AND_GEOMATIC_ENGINEERING",
                    "MECHANICAL_AND_PROCESS_ENGINEERING",
                    "COMPUTER_SCIENCE",
                    "MANAGEMENT_TECHNOLOGY_AND_ECONOMICS",
                    "MATHEMATICS",
                    "PHYSICS",
                    "BIOLOGY",
                    "EARTH_AND_PLANETARY_SCIENCES",
                    "HUMANITIES_SOCIAL_AND_POLITICAL_SCIENCES",
                    "INFORMATION_TECHNOLOGY_AND_ELECTRICAL_ENGINEERING",
                    "MATERIALS",
                    "CHEMISTRY_AND_APPLIED_BIOSCIENCES",
                    "BIOSYSTEMS_SCIENCE_AND_ENGINEERING",
                    "HEALTH_SCIENCES_AND_TECHNOLOGY",
                    "ENVIRONMENTAL_SYSTEMS_SCIENCE",
                    name="department",
                ),
                nullable=True,
            )
        )
        batch_op.create_unique_constraint(
            "learningunit_number_semkez", ["number", "semkez"]
        )
        batch_op.drop_column("code")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("learningunit", schema=None) as batch_op:
        batch_op.add_column(sa.Column("code", sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint("learningunit_number_semkez", type_="unique")
        batch_op.drop_column("department")
        batch_op.drop_column("levels")
        batch_op.drop_column("number")

    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.add_column(sa.Column("code", sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint("course_number_semkez", type_="unique")
        batch_op.drop_column("number")

    # ### end Alembic commands ###
