"""make departments plural

Revision ID: 77024f6fd0cc
Revises: 015faf174cb5
Create Date: 2025-12-21 20:54:59.626601

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77024f6fd0cc"
down_revision: Union[str, Sequence[str], None] = "015faf174cb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("learningunit", schema=None) as batch_op:
        batch_op.add_column(sa.Column("departments", sa.JSON(), nullable=True))

    op.execute(
        """
        UPDATE learningunit
        SET departments = JSON_ARRAY(department)
        WHERE department IS NOT NULL
        """
    )

    with op.batch_alter_table("learningunit", schema=None) as batch_op:
        batch_op.drop_column("department")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("learningunit", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("department", sa.VARCHAR(length=49), nullable=True)
        )

    op.execute(
        """
        UPDATE learningunit
        SET department = JSON_EXTRACT(departments, '$[0]')
        WHERE JSON_ARRAY_LENGTH(departments) > 0
        """
    )

    with op.batch_alter_table("learningunit", schema=None) as batch_op:
        batch_op.drop_column("departments")

    # ### end Alembic commands ###
