"""make lecturer title optional

Revision ID: 85ac8b35c9f8
Revises: d32f8010e741
Create Date: 2026-02-05 15:33:12.347943

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85ac8b35c9f8"
down_revision: Union[str, Sequence[str], None] = "d32f8010e741"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lecturer", schema=None) as batch_op:
        batch_op.alter_column("title", existing_type=sa.VARCHAR(), nullable=True)

    op.execute(
        """
        UPDATE lecturer
        SET title = NULL
        WHERE title = '';
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """
        UPDATE lecturer
        SET title = ''
        WHERE title IS NULL;
        """
    )

    with op.batch_alter_table("lecturer", schema=None) as batch_op:
        batch_op.alter_column("title", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
