"""init

Revision ID: a007ce80b4cb
Revises:
Create Date: 2025-10-19 14:59:22.063087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a007ce80b4cb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learningunit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title_english", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("semkez", sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
        sa.Column("credits", sa.Float(), nullable=True),
        sa.Column("two_semester_credits", sa.Float(), nullable=True),
        sa.Column("literature", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "literature_english", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("objective", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "objective_english", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content_english", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("lecture_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "lecture_notes_english", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("additional", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "additional_english", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("comment_english", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("max_places", sa.Integer(), nullable=True),
        sa.Column("waitlist_end", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("signup_end", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("signup_start", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("priority", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("primary_target_group", sa.JSON(), nullable=True),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("abstract", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "abstract_english", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("competencies", sa.JSON(), nullable=True),
        sa.Column("competencies_english", sa.JSON(), nullable=True),
        sa.Column("regulations", sa.JSON(), nullable=True),
        sa.Column("written_aids", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("additional_info", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("exam_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("exam_language", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("exam_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("exam_block", sa.JSON(), nullable=True),
        sa.Column("digital", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("distance_exam", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("repetition", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("groups", sa.JSON(), nullable=True),
        sa.Column(
            "course_frequency",
            sa.Enum("ONETIME", "ANNUAL", "SEMESTER", name="periodicity"),
            nullable=True,
        ),
        sa.Column("learning_materials", sa.JSON(), nullable=True),
        sa.Column("learning_materials_english", sa.JSON(), nullable=True),
        sa.Column(
            "occurence",
            sa.Enum("NO", "YES", "CANCELLED", name="occurenceenum"),
            nullable=True,
        ),
        sa.Column(
            "general_restrictions", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("examiners", sa.JSON(), nullable=True),
        sa.Column("lecturers", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "semkez"),
    )
    op.create_table(
        "lecturer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("surname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("golden_owl", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "section",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("semkez", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name_english", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("comment_english", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "course",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("semkez", sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
        sa.Column(
            "type",
            sa.Enum("V", "G", "U", "S", "K", "P", "A", "D", "R", name="coursetypeenum"),
            nullable=True,
        ),
        sa.Column("hours", sa.Float(), nullable=True),
        sa.Column(
            "hour_type",
            sa.Enum("WEEKLY_HOURS", "SEMESTER_HOURS", name="coursehourenum"),
            nullable=True,
        ),
        sa.Column(
            "comment", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("timeslots", sa.JSON(), nullable=True),
        sa.Column("lecturers", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["unit_id"], ["learningunit.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "semkez"),
    )
    op.create_table(
        "unitsectionlink",
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("O", "WPlus", "W", "EMinus", "Z", "Dr", name="unittypeenum"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["section_id"], ["section.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["learningunit.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("unit_id", "section_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unitsectionlink")
    op.drop_table("course")
    op.drop_table("section")
    op.drop_table("lecturer")
    op.drop_table("learningunit")
    # ### end Alembic commands ###
