"""add indices to links

Revision ID: aa860aba0a9f
Revises: dd4c19c96b3f
Create Date: 2026-02-20 20:53:23.900772

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa860aba0a9f"
down_revision: Union[str, Sequence[str], None] = "dd4c19c96b3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_course_unit_id"), ["unit_id"], unique=False
        )

    with op.batch_alter_table("unitexaminerlink", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_unitexaminerlink_lecturer_id"), ["lecturer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_unitexaminerlink_unit_id"), ["unit_id"], unique=False
        )

    with op.batch_alter_table("unitlecturerlink", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_unitlecturerlink_lecturer_id"), ["lecturer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_unitlecturerlink_unit_id"), ["unit_id"], unique=False
        )

    with op.batch_alter_table("unitsectionlink", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_unitsectionlink_section_id"), ["section_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_unitsectionlink_unit_id"), ["unit_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("unitsectionlink", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_unitsectionlink_unit_id"))
        batch_op.drop_index(batch_op.f("ix_unitsectionlink_section_id"))

    with op.batch_alter_table("unitlecturerlink", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_unitlecturerlink_unit_id"))
        batch_op.drop_index(batch_op.f("ix_unitlecturerlink_lecturer_id"))

    with op.batch_alter_table("unitexaminerlink", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_unitexaminerlink_unit_id"))
        batch_op.drop_index(batch_op.f("ix_unitexaminerlink_lecturer_id"))

    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_course_unit_id"))
    # ### end Alembic commands ###
