"""add

Revision ID: b6f18216363f
Revises: ffc22d4f857d
Create Date: 2025-10-18 18:23:27.557729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b6f18216363f'
down_revision: Union[str, Sequence[str], None] = 'ffc22d4f857d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lehrveranstaltung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lehrveranstaltung', schema=None) as batch_op:
        batch_op.drop_column('unit_id')

    # ### end Alembic commands ###
