"""add unit_id to course PK

Revision ID: bf994b267478
Revises: 788bae6774a2
Create Date: 2025-10-27 07:11:05.887466

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "bf994b267478"
down_revision: Union[str, Sequence[str], None] = "788bae6774a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: we just drop the old table to recreate it
    op.drop_table("course")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("semkez", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("V", "G", "U", "S", "K", "P", "A", "D", "R", name="coursetypeenum"),
            nullable=True,
        ),
        sa.Column("hours", sa.Float(), nullable=True),
        sa.Column(
            "hour_type",
            sa.Enum("WEEKLY_HOURS", "SEMESTER_HOURS", name="coursehourenum"),
            nullable=True,
        ),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("timeslots", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("number", "semkez", "unit_id"),
    )

    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "scraped_at", sa.Integer(), nullable=False, server_default=sa.text("0")
            )
        )

    with op.batch_alter_table("learningunit", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "scraped_at", sa.Integer(), nullable=False, server_default=sa.text("0")
            )
        )

    with op.batch_alter_table("lecturer", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "scraped_at", sa.Integer(), nullable=False, server_default=sa.text("0")
            )
        )

    with op.batch_alter_table("section", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "scraped_at", sa.Integer(), nullable=False, server_default=sa.text("0")
            )
        )

    with op.batch_alter_table("unittypelegends", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "scraped_at", sa.Integer(), nullable=False, server_default=sa.text("0")
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("unittypelegends", schema=None) as batch_op:
        batch_op.drop_column("scraped_at")

    with op.batch_alter_table("section", schema=None) as batch_op:
        batch_op.drop_column("scraped_at")

    with op.batch_alter_table("lecturer", schema=None) as batch_op:
        batch_op.drop_column("scraped_at")

    with op.batch_alter_table("learningunit", schema=None) as batch_op:
        batch_op.drop_column("scraped_at")

    with op.batch_alter_table("course", schema=None) as batch_op:
        batch_op.drop_column("scraped_at")

    op.drop_table("course")

    op.create_table(
        "course",
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("semkez", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("V", "G", "U", "S", "K", "P", "A", "D", "R", name="coursetypeenum"),
            nullable=True,
        ),
        sa.Column("hours", sa.Float(), nullable=True),
        sa.Column(
            "hour_type",
            sa.Enum("WEEKLY_HOURS", "SEMESTER_HOURS", name="coursehourenum"),
            nullable=True,
        ),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("timeslots", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("number", "semkez"),
    )
    # ### end Alembic commands ###
