"""add coursereview ratings

Revision ID: c87f2be09719
Revises: 85ac8b35c9f8
Create Date: 2026-02-11 23:31:48.393089

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c87f2be09719"
down_revision: Union[str, Sequence[str], None] = "85ac8b35c9f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rating",
        sa.Column("course_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recommended", sa.Float(), nullable=False),
        sa.Column("engaging", sa.Float(), nullable=False),
        sa.Column("difficulty", sa.Float(), nullable=False),
        sa.Column("effort", sa.Float(), nullable=False),
        sa.Column("resources", sa.Float(), nullable=False),
        sa.Column("scraped_at", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("course_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rating")
    # ### end Alembic commands ###
