"""add more lecturer infos

Revision ID: d32f8010e741
Revises: 77024f6fd0cc
Create Date: 2026-02-04 18:01:22.752587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd32f8010e741'
down_revision: Union[str, Sequence[str], None] = '77024f6fd0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
        
    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.alter_column('title', server_default=None)
        batch_op.alter_column('department', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
