"""init

Revision ID: d8610f775ae8
Revises: 
Create Date: 2025-10-15 14:03:59.319313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd8610f775ae8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abschnittdaten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('titelen', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('nummer', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('typ', sa.Integer(), nullable=True),
    sa.Column('typstringkurz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('typstringkurzen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('typstringlang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('typstringlangen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semkez', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('uebergeordneteabschnittid', sa.Integer(), nullable=True),
    sa.Column('reihenfolge', sa.Integer(), nullable=True),
    sa.Column('angezeigterkommentar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('angezeigterkommentaren', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abschnittelement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abschnittelementtyp', sa.Integer(), nullable=False),
    sa.Column('abschnittdaten_id', sa.Integer(), nullable=True),
    sa.Column('abschnittreferenz_id', sa.Integer(), nullable=True),
    sa.Column('lerneinheit_id', sa.Integer(), nullable=True),
    sa.Column('kinderelemente_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abschnittsrefernz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referenzierteabschnittsid', sa.Integer(), nullable=True),
    sa.Column('homeabschnittid', sa.Integer(), nullable=True),
    sa.Column('typ', sa.Integer(), nullable=True),
    sa.Column('typstringkurz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('typstringkurzen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('typstringlang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('typstringlangen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kommentar', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('kommentaren', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('belegungsserieort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veranstaltungsid', sa.Integer(), nullable=True),
    sa.Column('veranstaltungsortid', sa.Integer(), nullable=True),
    sa.Column('gebaeude', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('geschoss', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raum', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uhrzeitvon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uhrzeitbis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('areal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('datumvon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('datumbis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('typ', sa.Integer(), nullable=True),
    sa.Column('typstringkurz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('typstringkurzen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('typstringlang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('typstringlangen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wochentag', sa.Integer(), nullable=True),
    sa.Column('wochentagstringkurz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wochentagstringkurzen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wochentagstringlang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wochentagstringlangen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semesterbezugstyp', sa.Integer(), nullable=True),
    sa.Column('semesterbezugstypstringkurz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semesterbezugstypstringkurzen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semesterbezugstypstringlang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semesterbezugstypstringlangen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orttyp', sa.Integer(), nullable=True),
    sa.Column('orttypstringkurz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orttypstringkurzen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orttypstringlang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orttypstringlangen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ortsangabetyp', sa.Integer(), nullable=True),
    sa.Column('ortsangabetypstringkurz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ortsangabetypstringkurzen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ortsangabetypstringlang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ortsangabetypstringlangen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('periodizitaet', sa.Integer(), nullable=True),
    sa.Column('periodizitaetstringkurz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('periodizitaetstringkurzen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('periodizitaetstringlang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('periodizitaetstringlangen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wochendeltabeginn', sa.Integer(), nullable=True),
    sa.Column('wochendeltaende', sa.Integer(), nullable=True),
    sa.Column('vorarbeitungszeit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nachbereitungszeit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semkez', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lehrveranstalter',
    sa.Column('dozide', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vorname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('golden_owl', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('dozide')
    )
    op.create_table('lehrveranstaltung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nummer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('titel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semkez', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('typ', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('semesterbezug', sa.Integer(), nullable=True),
    sa.Column('semesterbezugstringkurz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semesterbezugstringkurzen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semesterbezugstringlang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semesterbezugstringlangen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lehrumfang', sa.Float(), nullable=True),
    sa.Column('lehrumfangtyp', sa.Integer(), nullable=True),
    sa.Column('lehrumfangtypstringkurz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lehrumfangtypstringkurzen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lehrumfangtypstringlang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lehrumfangtypstringlangen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('findetstatt', sa.Integer(), nullable=True),
    sa.Column('findetstattstringkurz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('findetstattstringkurzen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('findetstattstringlang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('findetstattstringlangen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('servicetyp', sa.Integer(), nullable=True),
    sa.Column('servicetypstringkurz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('servicetypstringkurzen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('servicetypstringlang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('servicetypstringlangen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('periodizitaet', sa.Integer(), nullable=True),
    sa.Column('periodizitaetstringkurz', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('periodizitaetstringkurzen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('periodizitaetstringlang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('periodizitaetstringlangen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nachvereinbarung', sa.Boolean(), nullable=True),
    sa.Column('dozentauswaehlen', sa.Boolean(), nullable=True),
    sa.Column('lehrsprache', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('spezialbewilligung', sa.Boolean(), nullable=True),
    sa.Column('externehoerer', sa.Boolean(), nullable=True),
    sa.Column('angezeigterkommentar', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('lehrveranstalter', sa.JSON(), nullable=True),
    sa.Column('belegungsserien', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lerneinheit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True),
    sa.Column('titel', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('titelenglisch', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('semkez', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('kreditpunkte', sa.Float(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('literatur', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('literaturenglisch', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('lernziel', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('lernzielenglisch', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('inhalt', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('inhaltenglisch', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('skript', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('skriptenglisch', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('besonderes', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('besonderesenglisch', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('diplomasupplement', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('diplomasupplementenglisch', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('angezeigterkommentar', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('angezeigterkommentaren', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('sternkollonne', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('belegungMaxPlatzzahl', sa.Integer(), nullable=True),
    sa.Column('belegungTermin2Wl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('belegungTermin3Ende', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('belegungsTerminStart', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vorrang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semester',
    sa.Column('semkez', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('semesterkurz', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('semesterlang', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('semesterlangen', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=False),
    sa.Column('semesterbeginn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semestermitte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semesterende', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semesterintervallende', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('abschnittelemente', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('semkez')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('semester')
    op.drop_table('lerneinheit')
    op.drop_table('lehrveranstaltung')
    op.drop_table('lehrveranstalter')
    op.drop_table('belegungsserieort')
    op.drop_table('abschnittsrefernz')
    op.drop_table('abschnittelement')
    op.drop_table('abschnittdaten')
    # ### end Alembic commands ###
