"""add unit changes table

Revision ID: dc051fb507e8
Revises: bf994b267478
Create Date: 2025-10-27 18:25:48.630103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc051fb507e8"
down_revision: Union[str, Sequence[str], None] = "bf994b267478"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unitchanges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column("scraped_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unitchanges")
    # ### end Alembic commands ###
