"""materialized departments

Revision ID: dd4c19c96b3f
Revises: 4a9111aae04a
Create Date: 2026-02-20 14:55:05.957413

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd4c19c96b3f"
down_revision: Union[str, Sequence[str], None] = "4a9111aae04a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unitdepartmentview",
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("unit_id", "department_id"),
    )

    with op.batch_alter_table("unitdepartmentview", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_unitdepartmentview_department_id"),
            ["department_id"],
            unique=False,
        )

    op.execute("""
        INSERT INTO unitdepartmentview (unit_id, department_id)
        SELECT
            learningunit.id AS unit_id,
            CAST(json_each.value AS INTEGER) AS department_id
        FROM learningunit, json_each(learningunit.departments)
        WHERE learningunit.departments IS NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("unitdepartmentview", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_unitdepartmentview_department_id"))

    op.drop_table("unitdepartmentview")
    # ### end Alembic commands ###
