"""groups signup end

Revision ID: e5534c6064e2
Revises: 497216f8f2a4
Create Date: 2025-10-29 21:08:38.593907

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e5534c6064e2"
down_revision: Union[str, Sequence[str], None] = "497216f8f2a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("learningunit", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "groups_signup_end", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )

    op.execute(sa.text("UPDATE learningunit SET groups='[]'"))
    op.execute(sa.text("UPDATE course SET timeslots='[]'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("UPDATE learningunit SET groups='{}'"))
    op.execute(sa.text("UPDATE course SET timeslots='[]'"))

    with op.batch_alter_table("learningunit", schema=None) as batch_op:
        batch_op.drop_column("groups_signup_end")

    # ### end Alembic commands ###
