"""add

Revision ID: f5c19471f37c
Revises: b6f18216363f
Create Date: 2025-10-18 19:18:11.117365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f5c19471f37c'
down_revision: Union[str, Sequence[str], None] = 'b6f18216363f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('semkez', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name_english', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comment_english', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('abschnittelement')
    op.drop_table('abschnittdaten')
    op.drop_table('belegungsserieort')
    op.drop_table('abschnittsrefernz')
    with op.batch_alter_table('lerneinheit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offered_in', sa.JSON(), nullable=True))

    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.drop_column('abschnittelemente')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abschnittelemente', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('lerneinheit', schema=None) as batch_op:
        batch_op.drop_column('offered_in')

    op.create_table('abschnittsrefernz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('referenzierteabschnittsid', sa.INTEGER(), nullable=True),
    sa.Column('homeabschnittid', sa.INTEGER(), nullable=True),
    sa.Column('typ', sa.INTEGER(), nullable=True),
    sa.Column('typstringkurz', sa.VARCHAR(), nullable=True),
    sa.Column('typstringkurzen', sa.VARCHAR(), nullable=True),
    sa.Column('typstringlang', sa.VARCHAR(), nullable=True),
    sa.Column('typstringlangen', sa.VARCHAR(), nullable=True),
    sa.Column('kommentar', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('kommentaren', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('belegungsserieort',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('veranstaltungsid', sa.INTEGER(), nullable=True),
    sa.Column('veranstaltungsortid', sa.INTEGER(), nullable=True),
    sa.Column('gebaeude', sa.VARCHAR(), nullable=True),
    sa.Column('geschoss', sa.VARCHAR(), nullable=True),
    sa.Column('raum', sa.VARCHAR(), nullable=True),
    sa.Column('uhrzeitvon', sa.VARCHAR(), nullable=True),
    sa.Column('uhrzeitbis', sa.VARCHAR(), nullable=True),
    sa.Column('region', sa.VARCHAR(), nullable=True),
    sa.Column('areal', sa.VARCHAR(), nullable=True),
    sa.Column('datumvon', sa.VARCHAR(), nullable=True),
    sa.Column('datumbis', sa.VARCHAR(), nullable=True),
    sa.Column('typ', sa.INTEGER(), nullable=True),
    sa.Column('typstringkurz', sa.VARCHAR(), nullable=True),
    sa.Column('typstringkurzen', sa.VARCHAR(), nullable=True),
    sa.Column('typstringlang', sa.VARCHAR(), nullable=True),
    sa.Column('typstringlangen', sa.VARCHAR(), nullable=True),
    sa.Column('wochentag', sa.INTEGER(), nullable=True),
    sa.Column('wochentagstringkurz', sa.VARCHAR(), nullable=True),
    sa.Column('wochentagstringkurzen', sa.VARCHAR(), nullable=True),
    sa.Column('wochentagstringlang', sa.VARCHAR(), nullable=True),
    sa.Column('wochentagstringlangen', sa.VARCHAR(), nullable=True),
    sa.Column('semesterbezugstyp', sa.INTEGER(), nullable=True),
    sa.Column('semesterbezugstypstringkurz', sa.VARCHAR(), nullable=True),
    sa.Column('semesterbezugstypstringkurzen', sa.VARCHAR(), nullable=True),
    sa.Column('semesterbezugstypstringlang', sa.VARCHAR(), nullable=True),
    sa.Column('semesterbezugstypstringlangen', sa.VARCHAR(), nullable=True),
    sa.Column('orttyp', sa.INTEGER(), nullable=True),
    sa.Column('orttypstringkurz', sa.VARCHAR(), nullable=True),
    sa.Column('orttypstringkurzen', sa.VARCHAR(), nullable=True),
    sa.Column('orttypstringlang', sa.VARCHAR(), nullable=True),
    sa.Column('orttypstringlangen', sa.VARCHAR(), nullable=True),
    sa.Column('ortsangabetyp', sa.INTEGER(), nullable=True),
    sa.Column('ortsangabetypstringkurz', sa.VARCHAR(), nullable=True),
    sa.Column('ortsangabetypstringkurzen', sa.VARCHAR(), nullable=True),
    sa.Column('ortsangabetypstringlang', sa.VARCHAR(), nullable=True),
    sa.Column('ortsangabetypstringlangen', sa.VARCHAR(), nullable=True),
    sa.Column('periodizitaet', sa.INTEGER(), nullable=True),
    sa.Column('periodizitaetstringkurz', sa.VARCHAR(), nullable=True),
    sa.Column('periodizitaetstringkurzen', sa.VARCHAR(), nullable=True),
    sa.Column('periodizitaetstringlang', sa.VARCHAR(), nullable=True),
    sa.Column('periodizitaetstringlangen', sa.VARCHAR(), nullable=True),
    sa.Column('wochendeltabeginn', sa.INTEGER(), nullable=True),
    sa.Column('wochendeltaende', sa.INTEGER(), nullable=True),
    sa.Column('vorarbeitungszeit', sa.VARCHAR(), nullable=True),
    sa.Column('nachbereitungszeit', sa.VARCHAR(), nullable=True),
    sa.Column('semkez', sa.VARCHAR(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abschnittdaten',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titel', sa.VARCHAR(length=250), nullable=True),
    sa.Column('titelen', sa.VARCHAR(length=250), nullable=True),
    sa.Column('nummer', sa.VARCHAR(length=8), nullable=True),
    sa.Column('typ', sa.INTEGER(), nullable=True),
    sa.Column('typstringkurz', sa.VARCHAR(), nullable=True),
    sa.Column('typstringkurzen', sa.VARCHAR(), nullable=True),
    sa.Column('typstringlang', sa.VARCHAR(), nullable=True),
    sa.Column('typstringlangen', sa.VARCHAR(), nullable=True),
    sa.Column('semkez', sa.VARCHAR(length=5), nullable=True),
    sa.Column('uebergeordneteabschnittid', sa.INTEGER(), nullable=True),
    sa.Column('reihenfolge', sa.INTEGER(), nullable=True),
    sa.Column('angezeigterkommentar', sa.VARCHAR(), nullable=True),
    sa.Column('angezeigterkommentaren', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abschnittelement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('abschnittelementtyp', sa.INTEGER(), nullable=False),
    sa.Column('abschnittdaten_id', sa.INTEGER(), nullable=True),
    sa.Column('abschnittreferenz_id', sa.INTEGER(), nullable=True),
    sa.Column('lerneinheit_id', sa.INTEGER(), nullable=True),
    sa.Column('kinderelemente_ids', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('section')
    # ### end Alembic commands ###
