"""add

Revision ID: ffc22d4f857d
Revises: 131e43fd572f
Create Date: 2025-10-18 17:37:32.768916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ffc22d4f857d'
down_revision: Union[str, Sequence[str], None] = '131e43fd572f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lerneinheit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('general_restrictions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lerneinheit', schema=None) as batch_op:
        batch_op.drop_column('general_restrictions')

    # ### end Alembic commands ###
