"""add flagged

Revision ID: 357b241a4250
Revises: c28cde0a90db
Create Date: 2026-02-27 22:17:37.706745

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "357b241a4250"
down_revision: Union[str, Sequence[str], None] = "c28cde0a90db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("httpcache", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "flagged", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )

    with op.batch_alter_table("httpcache", schema=None) as batch_op:
        batch_op.alter_column("flagged", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("httpcache", schema=None) as batch_op:
        batch_op.drop_column("flagged")

    # ### end Alembic commands ###
