"""httpcache table

Revision ID: fd345d2b7d78
Revises:
Create Date: 2026-02-27 17:45:49.644585

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd345d2b7d78"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "httpcache",
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("body", sa.LargeBinary(), nullable=True),
        sa.Column("headers", sa.JSON(), nullable=True),
        sa.Column("scraped_at", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("url"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("httpcache")
    # ### end Alembic commands ###
