FROM astral/uv:python3.13-trixie-slim

WORKDIR /app

COPY uv.lock pyproject.toml .python-version alembic.ini scrapy.cfg ./ 
COPY scraper scraper
COPY api api
COPY alembic alembic

RUN uv sync

CMD uv run alembic upgrade heads && uv run -m scraper.main
