FROM astral/uv:python3.13-trixie-slim

WORKDIR /app

COPY uv.lock pyproject.toml .python-version alembic.ini ./ 
COPY api api
COPY alembic alembic
# allows for debugging in the api pod
COPY scraper scraper

RUN uv sync

CMD uv run alembic upgrade heads && uv run fastapi run api/main.py
