from sqlmodel import Field
from api.new_models.basemodel import BaseModel


class BelegungsserieOrt(BaseModel, table=True):
    """WsBelegungsSerieOrt"""

    id: int = Field(primary_key=True)
    veranstaltungsid: int | None = Field(default=None)  # FK expected
    veranstaltungsortid: int | None = Field(default=None)
    gebaeude: str | None = Field(default=None)
    geschoss: str | None = Field(default=None)
    raum: str | None = Field(default=None)
    uhrzeitvon: str | None = Field(default=None)
    uhrzeitbis: str | None = Field(default=None)
    region: str | None = Field(default=None)
    areal: str | None = Field(default=None)
    datumvon: str | None = Field(default=None)
    datumbis: str | None = Field(default=None)
    typ: int | None = Field(default=None)
    typstringkurz: str | None = Field(default=None)
    typstringkurzen: str | None = Field(default=None)
    typstringlang: str | None = Field(default=None)
    typstringlangen: str | None = Field(default=None)
    wochentag: int | None = Field(default=None)
    wochentagstringkurz: str | None = Field(default=None)
    wochentagstringkurzen: str | None = Field(default=None)
    wochentagstringlang: str | None = Field(default=None)
    wochentagstringlangen: str | None = Field(default=None)
    semesterbezugstyp: int | None = Field(default=None)
    semesterbezugstypstringkurz: str | None = Field(default=None)
    semesterbezugstypstringkurzen: str | None = Field(default=None)
    semesterbezugstypstringlang: str | None = Field(default=None)
    semesterbezugstypstringlangen: str | None = Field(default=None)
    orttyp: int | None = Field(default=None)
    orttypstringkurz: str | None = Field(default=None)
    orttypstringkurzen: str | None = Field(default=None)
    orttypstringlang: str | None = Field(default=None)
    orttypstringlangen: str | None = Field(default=None)
    ortsangabetyp: int | None = Field(default=None)
    ortsangabetypstringkurz: str | None = Field(default=None)
    ortsangabetypstringkurzen: str | None = Field(default=None)
    ortsangabetypstringlang: str | None = Field(default=None)
    ortsangabetypstringlangen: str | None = Field(default=None)
    periodizitaet: int | None = Field(default=None)
    periodizitaetstringkurz: str | None = Field(default=None)
    periodizitaetstringkurzen: str | None = Field(default=None)
    periodizitaetstringlang: str | None = Field(default=None)
    periodizitaetstringlangen: str | None = Field(default=None)
    wochendeltabeginn: int | None = Field(default=None)
    wochendeltaende: int | None = Field(default=None)
    vorarbeitungszeit: str | None = Field(default=None)
    nachbereitungszeit: str | None = Field(default=None)
    semkez: str | None = Field(default=None, max_length=5)
