name: Type check and Build

on:
  push:
    paths:
      - "**.py"
      - "**.html"
      - "**.yml"
      - "uv.lock"
      - "Dockerfile"
  release:
    types: [created]

jobs:
  test:
    name: Test types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.9.2"

      - name: Install sqlite3
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3

      - run: uv sync --all-extras

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Check SQLite Alembic Migrations
        run: |
          uv run alembic upgrade heads
          uv run alembic check
          uv run alembic downgrade base
          uv run alembic upgrade heads
          uv run alembic check

  build:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Determine API tags
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
            # Remove leading 'v' if present
            VERSION="${VERSION#v}"
            MAJOR=$(echo $VERSION | cut -d. -f1)
            MINOR=$(echo $VERSION | cut -d. -f2)
            PATCH=$(echo $VERSION | cut -d. -f3)
            echo "::set-output name=tags::${{ secrets.DOCKER_HUB_USERNAME }}/vvzapi:$VERSION,${{ secrets.DOCKER_HUB_USERNAME }}/vvzapi:$MAJOR.$MINOR,${{ secrets.DOCKER_HUB_USERNAME }}/vvzapi:$MAJOR,${{ secrets.DOCKER_HUB_USERNAME }}/vvzapi:latest"
            echo "::set-output name=version::$VERSION"
          else
            echo "::set-output name=tags::${{ secrets.DOCKER_HUB_USERNAME }}/vvzapi:nightly"
            github_sha_hash=${{ github.sha }}
            echo "::set-output name=version::nightly:${github_sha_hash:0:7}"
          fi

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          file: deploy/Dockerfile.api
          platforms: linux/amd64
          push: true
          tags: ${{ steps.vars.outputs.tags }}
          build-args: |
            VERSION=${{ steps.vars.outputs.version }}

      - name: Determine scraper tags
        id: vars-scraper
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
            # Remove leading 'v' if present
            VERSION="${VERSION#v}"
            MAJOR=$(echo $VERSION | cut -d. -f1)
            MINOR=$(echo $VERSION | cut -d. -f2)
            PATCH=$(echo $VERSION | cut -d. -f3)
            echo "::set-output name=tags::${{ secrets.DOCKER_HUB_USERNAME }}/vvzapi-scraper:$VERSION,${{ secrets.DOCKER_HUB_USERNAME }}/vvzapi-scraper:$MAJOR.$MINOR,${{ secrets.DOCKER_HUB_USERNAME }}/vvzapi-scraper:$MAJOR,${{ secrets.DOCKER_HUB_USERNAME }}/vvzapi-scraper:latest"
            echo "::set-output name=version::$VERSION"
          else
            echo "::set-output name=tags::${{ secrets.DOCKER_HUB_USERNAME }}/vvzapi-scraper:nightly"
            github_sha_hash=${{ github.sha }}
            echo "::set-output name=version::nightly:${github_sha_hash:0:7}"
          fi

      - name: Build and push scraper
        uses: docker/build-push-action@v5
        with:
          file: deploy/Dockerfile.scraper
          platforms: linux/amd64
          push: true
          tags: ${{ steps.vars-scraper.outputs.tags }}
          build-args: |
            VERSION=${{ steps.vars-scraper.outputs.version }}
